spring:
    profiles:
        active: development
    output:
        ansi:
            enabled: ALWAYS
    mvc:
        favicon:
            enabled: false
server:
    port: 8000
app:
    token:
        signature-algorithm: RS512
        expiration-time: 1800_000
    singpass:
        identity-provider:
            artifact-lifetime-clock-skew: 60_000
---

spring:
    profiles: development
app:
    instrumentation:
        zipkin:
            env: dev
    singpass:
        homepage-url: http://localhost:3000/
        service-provider:
            login-url: http://localhost:4000/login
    corppass:
        homepage-url: http://localhost:3001/
        service-provider:
            login-url: http://localhost:4000/login

---

spring:
    profiles: production
app:
    instrumentation:
        zipkin:
            env: prod
    singpass:
        homepage-url: https://www.mysite.sg/
        service-provider:
            login-url: https://api.mysite.sg/login
            metadata-path: /app/shared/metadata/sp_singpass.xml
            metadata-id: SpSingpass
        identity-provider:
            host: saml.singpass.gov.sg
            service-id: SERVICE-ID-SP-2FA
            metadata-path: /app/shared/metadata/idp_singpass.xml
            metadata-id: IdpSingpass
    corppass:
        homepage-url: https://corp.mysite.sg/
        service-provider:
            login-url: https://api.mysite.sg/login
            metadata-path: /app/shared/metadata/sp_corppass.xml
            metadata-id: SpCorppass
        identity-provider:
            host: saml.corppass.gov.sg
            service-id: SERVICE-ID-CP-2FA
            metadata-path: /app/shared/metadata/idp_corppass.xml
            metadata-id: IdpCorppass
